# Generated by Django 4.2.16 on 2026-06-26 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=128, unique=True)),
                ("balance", models.BigIntegerField(default=1000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerSeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=128, unique=True)),
                ("server_seed", models.CharField(max_length=64)),
                ("server_seed_hash", models.CharField(max_length=64)),
                ("client_seed", models.CharField(default="", max_length=128)),
                ("nonce", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=128)),
                ("bet", models.IntegerField()),
                ("reels", models.JSONField()),
                ("count", models.IntegerField()),
                ("symbol", models.IntegerField()),
                ("base_win", models.IntegerField()),
                ("phase", models.IntegerField(default=0)),
                ("pot", models.IntegerField(default=0)),
                ("risk_steps", models.IntegerField(default=0)),
                ("status", models.CharField(default="active", max_length=8)),
                ("server_seed_hash", models.CharField(max_length=64)),
                ("client_seed", models.CharField(max_length=128)),
                ("nonce", models.BigIntegerField()),
                ("server_seed", models.CharField(default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
